### ISSUE TITLE
child process STDIN is not a real system file handle - auth with password already given

### ISSUE THREAD

**Issue by vshast** [salva/p5-Net-OpenSSH#30] opened 2021-11-20 10:55 UTC
Hi,
This code
                                                my $ssh = Net::OpenSSH->new(
                                                                ‘sftp_addr’,
                                                                user => 'sftp_user',
                                                                password => 'sftp_password'
                                                );
called from some places crashes in some cases in our project:

child process STDIN is not a real system file handle

 In the same project called from some other places it works correctly.
 I can't check underlying conditions, so I just tried to add this line 
 
 open STDIN, "</dev/null";
 
 before the code. It caused the next error -
 
 unable to load Perl module IO::Pty.
 
 But if I've already set password => 'sftp_password', I don't need any STDIN functionality...

**Comment by salva** [comment] 2022-03-05 22:39
The issue description is quite confusing and doesn't allow me to reproduce the issue, and anyway, it looks like a FAQ (https://metacpan.org/pod/Net::OpenSSH#child-process-STDIN/STDOUT/STDERR-is-not-a-real-system-file-handle), so, I am closing it.

If you still need help solving the issue, I advice you to post it in Perlmonks or in StackOverflow.

**Closed by salva** 2022-03-05 22:39 UTC
